package com.appointments.spappoitmentsapi.controllers;

import com.appointments.spappoitmentsapi.dto.TestDTO;
import com.appointments.spappoitmentsapi.services.TestService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class TestControllerTest {

    @Mock
    private TestService testServiceMock;

    @InjectMocks
    private TestController underTest;

    @BeforeEach
    void setUp() {
        underTest = new TestController(testServiceMock);
    }

    @Test
    void getNotEmptyList() {
        List<TestDTO> testDTOListMocked = new ArrayList<>();
        TestDTO testDTO1 = new TestDTO();
        testDTO1.setId(1L);
        testDTO1.setName("TestName1");
        testDTO1.setDescription("TestDesc1");

        TestDTO testDTO2 = new TestDTO();
        testDTO2.setId(2L);
        testDTO2.setName("TestName2");
        testDTO2.setDescription("TestDesc2");

        testDTOListMocked.add(testDTO1);
        testDTOListMocked.add(testDTO2);

        when(testServiceMock.getAll()).thenReturn(testDTOListMocked);

        ResponseEntity<List<TestDTO>> response = underTest.getList();

        assertThat(response).isNotNull();
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(testDTOListMocked);
    }

    @Test
    void getEmptyList() {
        List<TestDTO> testDTOListMocked = new ArrayList<>();
        when(testServiceMock.getAll()).thenReturn(testDTOListMocked);
        ResponseEntity<List<TestDTO>> response = underTest.getList();

        assertThat(response).isNotNull();
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.NO_CONTENT);
        assertThat(response.getBody()).isNull();
    }

    @Test
    void postWithValidEntry() {
        TestDTO testToBeCreated = new TestDTO();
        testToBeCreated.setName("testName");
        testToBeCreated.setDescription("testDesc");

        TestDTO testCreatedMock = new TestDTO();
        testCreatedMock.setId(1L);
        testCreatedMock.setName(testCreatedMock.getName());
        testCreatedMock.setDescription(testCreatedMock.getDescription());

        when(testServiceMock.post(testToBeCreated)).thenReturn(testCreatedMock);

        ResponseEntity<TestDTO> response = underTest.post(testToBeCreated);

        assertThat(response).isNotNull();
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.CREATED);
        assertThat(response.getBody()).isEqualTo(testCreatedMock);
    }

    @Test
    void postWithNoValidEntry() {
        TestDTO testToBeCreated = new TestDTO();
        testToBeCreated.setId(1L); //Not valid entry, because Id must be null (DB autogenerated)
        testToBeCreated.setName("testName");
        testToBeCreated.setDescription("testDesc");

        when(testServiceMock.post(testToBeCreated)).thenReturn(null);

        ResponseEntity<TestDTO> response = underTest.post(testToBeCreated);

        assertThat(response).isNotNull();
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
        assertThat(response.getBody()).isNull();
    }

    @Test
    void postWithNullEntry() {
        ResponseEntity<TestDTO> response = underTest.post(null);
        assertThat(response).isNotNull();
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.BAD_REQUEST);
        assertThat(response.getBody()).isNull();
    }

    @Test
    void getExtistingTestByID() {
        TestDTO testMock = new TestDTO();
        testMock.setId(1L);
        testMock.setName("testName");
        testMock.setDescription("testDesc");

        when(testServiceMock.getByID(testMock.getId())).thenReturn(testMock);
        ResponseEntity<TestDTO> response = underTest.getByID(testMock.getId());

        assertThat(response).isNotNull();
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isEqualTo(testMock);
    }

    @Test
    void getNonExtistingTestByID() {
        TestDTO testMock = new TestDTO();
        testMock.setId(999L);
        testMock.setName("testName");
        testMock.setDescription("testDesc");

        when(testServiceMock.getByID(testMock.getId())).thenReturn(null);
        ResponseEntity<TestDTO> response = underTest.getByID(testMock.getId());

        assertThat(response).isNotNull();
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
        assertThat(response.getBody()).isNull();
    }

    @Test
    void put() {
    }

    @Test
    void delete() {
    }
}